version: '3'
services:
  app:
    build .
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  postgres:
    image: postgres:12.16
    ports:
      - "3030:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

